server:
  port: 8051
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8050/eureka/
spring:
  application:
    name: service-hi
  rabbitmq:
    addresses: 119.29.84.121:15672
    password: rabbitmq
    username: rabbitmq
    publisher-confirms: true #消息才会回调
    virtual-host: /
